### ISSUE TITLE
[1.11.2] Crashing a lot when veinmining - Exception in server tick loop

### ISSUE THREAD

**Issue by angelnc1989** [portablejim/VeinMiner#123]
Minecraft 1.11.2
Forge 13.20.1.2414
VeinMiner 0.36.0.621+8499b73

[Crash report](https://pastebin.com/za4Jvyxm)

The game crashes when vein mining ores. Sometimes the ores lie on the ground after restarting, sometimes they are just gone.

**Comment by AMartinie** [comment]
Getting the exact same crash, line-for-line. It's happening to me in both 1.10.2 and 1.11.2. I use sneak to activate veinminer. So far it only happens when i mine redstone ore.

**Comment by AMartinie** [comment]
Issue is still not resolved with VeinMiner 0.38.0 [MC1.9,1.9.4,1.10,1.10.2; rev 614]. 
As far as I'm aware, I can mine all ores except for Redstone. I crash roughly every 2-3 veins of redstone that I try to mine.  Again, I'm using Sneak to activate veinminer.   
  
So far, I can solve this crash completely just by disabling redstone via:
/veinminer blocklist pickaxe remove minecraft:redstone_ore

[Crash Report](https://pastebin.com/zVLErSGL)

**Comment by portablejim** [comment]
It's nuclearcraft that's blowing up (pun only partially intended), but I will try to address it next update.

**Comment by AMartinie** [comment]
If I remove nuclearcraft, the issue will be resolved? I don't even like nuclearcraft lol

**Comment by portablejim** [comment]
Try and and see.

**Comment by AMartinie** [comment]
Looks like you're correct. Ran a test world in AllTheMods1 with every mod except nuclearcraft and I can't recreate the bug. I have no issues veinmining redstone ore as long as nuclearcraft is removed.

**Comment by angelnc1989** [comment]
But I am not running Nuclearcraft.

**Comment by AMartinie** [comment]
Can you post your modlist?

**Comment by portablejim** [comment]
The first crash was fixed, then SadChimera posted about another one.. which I think I have also fixed.

**Comment by angelnc1989** [comment]
Just got the same crash in my 1.12 world on the latest VeinMiner version.
[Crash report](https://pastebin.com/7fbTFfdz)

**Comment by angelnc1989** [comment]
I have the feeling this happens mostly while chunks are being loaded around me. When I travel some distance into new or just unloaded chunks and go underground to mine it crashes a lot.

**Comment by AMartinie** [comment]
I used chickenchunk loaders and still crashed, but I haven't been on
minecraft to check in the past month

**Comment by angelnc1989** [comment]
I don't think it has anything to do with ChickenChunks. I crashed when I used them and when I didn't.

**Comment by AMartinie** [comment]
I just mean that I kept chunks loaded and crashed while in them. So
chunkloading isn't an issue. Though there was a crash with mclib when
teleporting into an unloaded chunk

**Comment by potatom4n** [comment]
im at 1.7.10 i use mac i dont use nuclear craft and veinminer crashes me
