### ISSUE TITLE
[1.10.2] Veinmined Blocks goto random open space than inventory//to player

### ISSUE THREAD

**Issue by Morpheus1101** [portablejim/VeinMiner#88]
When veinmining ore, often the veinmined ore appears to disappear, but instead has actually gone to an empty area rather than to the player.

https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/292

**Comment by portablejim** [comment]
Should be fixed with the latest release.

**Comment by Morpheus1101** [comment]
I shall do some testing in about 4-5hrs and shall let you know

**Comment by Shadows-of-Fire** [comment]
Why not just spawn it at the player's feet instead of trying to get it to spawn correctly on the block?

**Comment by portablejim** [comment]
To give a closer-to-normal chance that you will loose the items. (e.g. if you mine a vein of items that are almost out of reach when you are over lava and don't have a magnet, if you veinmine items on a skyblock)

**Comment by Morpheus1101** [comment]
This issue still occurs using most current version form curse

**Comment by portablejim** [comment]
Having trouble reproducing it. Can you give more specific info, such as the MC version (I will assume Veinminer 0.35.2) and maybe a screenshot of the setup you are using to reproduce it.

**Comment by Morpheus1101** [comment]
MC 1.10.2 using Forge *.2185 using either Stone Pickaxe from Minecraft to a Iron Pickaxe from Tinkers Construct and VM 0.35.2  .... It dosent happen every time, but frequent enough to call it common, setup well simply go mining is all i do using only a single pickaxe, no armour or weapons or enchantments etc

Occurs from normal Diamonds to other various ore's in this pack

**Comment by portablejim** [comment]
Ok, try 0.35.3.

**Comment by Morpheus1101** [comment]
Firing it up for testing....

**Comment by Morpheus1101** [comment]
From short testings it seems better.  More extensive long term testing is needed and if this should pop up i'll re-open this issue.
